# docker compose -f deploy/docker-compose.yml --env-file ./.env up --build
version: '3.8'

services:
  laravel:
    image: ghcr.io/zjx-artcc/site-laravel:master
    restart: unless-stopped
    container_name: zjx-laravel
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    volumes:
      - ../storage/app:/var/www/html/storage/app
    env_file:
        - ../.env.prod
    ports:
      - "8080:80"
    networks:
      - laravel
    extra_hosts:
        - "host.docker.internal:host-gateway"

  queue:
    image: ghcr.io/zjx-artcc/site-laravel:master
    container_name: laravel_queue
    restart: unless-stopped
    # Overwrite the default command to run the queue worker
    command: php artisan queue:work --tries=3 --timeout=90
    env_file:
        -   ../.env.prod
    depends_on:
        - laravel
    extra_hosts:
        - "host.docker.internal:host-gateway"

  scheduler:
    image: ghcr.io/zjx-artcc/site-laravel:master
    container_name: laravel_scheduler
    restart: unless-stopped
    # "schedule:work" runs the scheduler in the foreground (available in Laravel 8+)
    command: php artisan schedule:work
    depends_on:
        - laravel
    extra_hosts:
        - "host.docker.internal:host-gateway"

networks:
  laravel:
    driver: bridge

