<?php

namespace App\Models;

use App\Enums\EventType;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Event extends Model
{
    use HasFactory;

    private const BANNER_DIRECTORIES = ['event/', 'events/'];

    protected $fillable = [
        'title',
        'description',
        'start',
        'end',
        'type',
        'featured_fields',
        'hidden',
        'presetPositions',
        'event_image_route',
        'positions_locked',
        'published',
        'archived',
        'archived_at',
    ];

    protected $casts = [
        'type' => EventType::class,
        'start' => 'datetime',
        'end' => 'datetime',
        'featured_fields' => 'array',
        'hidden' => 'boolean',
        'positions_locked' => 'boolean',
        'published' => 'boolean',
        'presetPositions' => 'array',
        'archived' => 'boolean',
        'archived_at' => 'datetime',
    ];

    public function positionRequests()
    {
        return $this->hasMany(EventPosition::class);
    }

    public function getFormattedRangeAttribute()
    {
        return $this->start?->utc()->format('m/d/Y H:i:s').'z - '.$this->end?->utc()->format('m/d/Y H:i:s').'z';
    }

    public function getFormattedTimeAttribute()
    {
        return $this->start?->utc()->format('H:i:s').'z - '.$this->end?->utc()->format('H:i:s').'z';

    }

    /**
     * The browser-facing URL is generated by the configured public disk rather
     * than being assembled from the application's base URL. This keeps banners
     * working when public storage is served by a CDN or another configured URL.
     */
    protected function bannerUrl(): Attribute
    {
        return Attribute::get(function (): ?string {
            $path = $this->bannerStoragePath();

            return $path ? Storage::disk('public')->url($path) : null;
        });
    }

    /**
     * Returns a safe public-disk path for a banner, including rows saved before
     * banner paths stopped carrying the `storage/` URL prefix.
     */
    public function bannerStoragePath(): ?string
    {
        if (blank($this->event_image_route)) {
            return null;
        }

        $path = ltrim($this->event_image_route, '/');
        $path = str_starts_with($path, 'storage/') ? substr($path, strlen('storage/')) : $path;

        return collect(self::BANNER_DIRECTORIES)
            ->contains(fn (string $directory) => str_starts_with($path, $directory))
            ? $path
            : null;
    }

    /**
     * True only in the 24 hours before an event starts — deliberately not true
     * once the event is already underway.
     */
    public function isStartingSoon(): bool
    {
        return $this->start !== null && $this->start->between(now(), now()->addHours(24));
    }
}
