jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create .env file from GitHub Secret
        run: |
          echo "${{ secrets.ENV_FILE_PROD }}" > .env.prod

      - name: Deploy to Docker Swarm / Compose
        run: |
          # When you run deploy, it uses the file we just created
          docker stack deploy -c docker-compose.yml my_stack
