name: Run Tests in Docker

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-in-docker:
    runs-on: ubuntu-latest
    environment: Testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build Containers
        run: |
          docker compose -p test -f tests/docker-compose.yml build \
            --build-arg INSTALL_DEV=true

      - name: Start Services
        run: |
          docker compose -p test -f tests/docker-compose.yml up -d

      - name: Show Container Status
        run: |
          docker compose -p test -f tests/docker-compose.yml ps

      - name: Prepare SQLite Database
        run: |
          docker compose -p test -f tests/docker-compose.yml exec -T laravel \
            sh -c 'mkdir -p /var/www/html/storage/database && touch /var/www/html/storage/database/database.sqlite && chmod 666 /var/www/html/storage/database/database.sqlite'

      - name: Generate Laravel Application Key
        run: |
          docker compose -p test -f tests/docker-compose.yml exec -T laravel \
            sh -c 'touch /var/www/html/.env && php artisan key:generate --force'

      - name: Initialize Database
        run: |
          docker compose -p test -f tests/docker-compose.yml exec -T laravel \
            php artisan migrate --seed --force

      - name: Execute Tests
        run: |
          docker compose -p test -f tests/docker-compose.yml exec -T laravel \
            ./vendor/bin/pest

      - name: Teardown
        if: always()
        run: |
          docker compose -p test -f tests/docker-compose.yml down -v
